Repository fis-g4/frontend, pull requests merged in 2024-01, with the labels that each got.

#29 FEAT: RESPONSIVE LANDING
  client/src/components/landing-hero-mobile/landing-hero-mobile.tsx
  client/src/components/landing-popular-courses/landing-popular-courses.tsx
  client/src/components/landing-top-categories.tsx/landing-top-categories.tsx
  client/src/pages/landing.tsx
  client/src/static/backgrounds/fondoMobile.png
Labels: enhancement, deploy, design, users-team

#16 FEAT(#009): DESIGN PAGE FOR MATERIALS MANAGEMENT
  client/public/assets/icons/navbar/ic_folder.svg
  client/src/components/materials-files/material-card.tsx
  client/src/components/materials-files/materials-files.tsx
  client/src/components/materials-filter/materials-filter.tsx
  client/src/components/materials-form/materials-form.tsx
  client/src/components/pagination/pagination.tsx
  client/src/layouts/dashboard/config-navigation.tsx
  client/src/pages/materials.tsx
  client/src/routes/router.tsx
  client/src/utils/schemas.ts
Labels: enhancement, design, learning-team

#36 ADD MATERIALS PAGE AND FOLDER ICON TO NAVIGATION
  client/src/_mocks/materials.ts
  client/src/_mocks/users.ts
  client/src/components/materials-files/material-card.tsx
  client/src/components/materials-files/materials-files.tsx
  client/src/components/user-list/pagination.tsx
  client/src/components/user-list/user-list.tsx
  client/src/components/users-filter/users-filter.tsx
  client/src/components/users-list/pagination.tsx
  client/src/components/users-list/user-list.tsx
  client/src/pages/courses.tsx
  client/src/pages/materials.tsx
Labels: enhancement, learning-team

#39 IMPLEMENT USER LIST INTEGRATION AND CLASSES AND MATERIALS ON COURSES
  client/src/_mocks/materials.ts
  client/src/_mocks/users.ts
  client/src/api/useClassesApi.ts
  client/src/api/useMaterialsApi.ts
  client/src/components/materials-files/material-card.tsx
  client/src/components/materials-files/materials-files.tsx
  client/src/components/user-list/pagination.tsx
  client/src/components/user-list/user-list.tsx
  client/src/components/users-list/user-list.tsx
  client/src/pages/courses.tsx
  client/src/pages/materials.tsx
Labels: integration, learning-team

#32 FEAT(#007): ADD MATERIAL DETAILS PAGE
  client/package-lock.json
  client/package.json
  client/src/_mocks/materials.ts
  client/src/components/course-classes-materials/course-classes-materials.tsx
  client/src/components/course-classes-materials/course-materials.tsx
  client/src/components/course-lesson-details/course-lesson-details.tsx
  client/src/components/course-material-details/course-material-details.tsx
  client/src/pages/material-details.tsx
  client/src/routes/router.tsx
  client/tsconfig.json
Labels: enhancement, design, learning-team

#42 FEAT(#40): LINK MATERIALS CRUD FRONTEND WITH BACKEND
  client/src/api/useMaterialsApi.ts
  client/src/components/materials-files/material-card.tsx
  client/src/components/materials-files/materials-files.tsx
  client/src/components/materials-form/materials-form.tsx
  client/src/pages/materials.tsx
Labels: integration, learning-team

#17 FEAT(#003): FIRST FOOTER VERSION
  client/package-lock.json
  client/package.json
  client/public/docs/CA/Customer_Agreement_v0.4.html
  client/public/docs/CA/Customer_Agreement_v0.5.html
  client/public/docs/CA/Customer_Agreement_v0.6.html
  client/public/docs/CA/Customer_Agreement_v0.7.html
  client/public/docs/CA/Customer_Agreement_v0.8.html
  client/public/docs/CA/Customer_Agreement_v0.9.html
  client/public/docs/CA/Customer_Agreement_v1.0.html
  client/public/docs/CA/css/styles.css
  client/src/components/footer/footer.css
  client/src/components/footer/footer.tsx
  client/src/pages/contract.tsx
  client/src/routes/router.tsx
  client/src/static/icons/slack-svgrepo-com.svg
  client/src/static/icons/slack.svg
  package.json
Labels: enhancement, design, learning-team
